### ISSUE TITLE
Build and restli-tools-scala - first scan

### ISSUE THREAD

**Issue by FranklinYinanDing** [TylerHorth/sbt-restli#1]
- [x] Structure-wise, I prefer all projects on the same level, rather than a top level `src/` and also `restli-tools-scala`.
- [x] [pegasusVersion](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L1) doesn't need to be an SBT setting, could be just a val?
- [x] Talked offline, adding pegasus for consumer isn't ideal, we'd better let consumer add dependency by themselves and do version compatibility check.
- [x] [this dependency](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L19) seems to be redundant, as you are already having inter-module dependency.
- [x] [this special dependency](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L21) could be separated and add some comment for documentation.
- [x] [root](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L5) could also be lazy? And a better project val name than `root`?
- [x] [log4j version](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L32-L34) could be exacted out as a val. Same for [specs2](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L50-L51)
- [x] What's the intention of [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L58)
- [x] [Doc s Provider?](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L32)
- [x] nitpick and elsewhere too [scaladoc style instead?](https://github.com/TylerHorth/sbt-restli/blob/rewrite/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L31)
- [x] [not very Scala style](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L37), instead, you can have a default value in the constrctor above. Unless you are thinking this could be used in Java.
- [x] Is [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L41) an implementation? If so, it is better to add `override` keyword. Outside IDE, it is hard to differentiate. Elsewhere too. And also should inherit super's doc, unless you did something special here.
- [x] Usually, we try to avoid [state or var](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L39). Is this necessary for the workflow to work? And looks like it is always `None`?
- [x] [error => log.error(error)](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L45) could be `log.error(_)`.
- [x] [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L46-L50) could be simplified as `settings.usejavacp.value = (classpath == null) || classpath.mkString(":")` or `settings.usejavacp.value = Option(classpath).map(_.mkString(":")).getOrElse(true)`.
- [x] Is [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L70) because Scala doesn't usually use `@Deprecate`?
- [x] [This](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L103) could combine with the above line.
- [x] Could remove [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L109-L110) if not documented or you can fill in something. Same elsewhere.
- [x] [Here](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L181) also could be one-liner.

**Comment by TylerHorth** [comment]
> * [x]  What's the intention of [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/build.sbt#L58)

[Scripted](https://www.scala-sbt.org/1.0/docs/Testing-sbt-plugins.html) is the test runner for sbt tests. Scripted tests work by first publishing the plugin locally, then running scripts against each project under the `sbt-test` directory. This code passes the current plugin version to each test, which is used in the tests project/plugins.sbt file to add the locally published sb-restli dependency. 

> * [x]  [not very Scala style](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L37), instead, you can have a default value in the constrctor above. Unless you are thinking this could be used in Java.

It is used [from restli](https://github.com/linkedin/rest.li/blob/master/restli-tools/src/main/java/com/linkedin/restli/internal/tools/AdditionalDocProvidersUtil.java#L26). I haven't made any changes to the ScalaDocsProvider besides what was needed to get it building on scala 2.12. I'll have to look into compatibility requirements for java-scala binding, but it looks like only the DocsProvider interface and a no arguments constructor is needed. 

> * [x]  Usually, we try to avoid [state or var](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L39). Is this necessary for the workflow to work? And looks like it is always `None`?

This is set when `registerSourceFiles` is called (part of the DocsProvider interface), and used by the `findTemplate` method. 

> * [x]  [this](https://github.com/TylerHorth/sbt-restli/blob/7e9ffb7cb3fdc6b48e7aab04c17af1a012db1e94/restli-tools-scala/src/main/scala/com/linkedin/restli/tools/scala/ScalaDocsProvider.scala#L46-L50) could be simplified as `settings.usejavacp.value = (classpath == null) || classpath.mkString(":")` or `settings.usejavacp.value = Option(classpath).map(_.mkString(":")).getOrElse(true)`.

It's easy to miss, but this isn't actually equivalent: 
`settings.classpath` is a string, and should be generated from the `classpath` array if it's not null.
`settings.usejavacp` is a boolean, and should be set to true if `classpath` is null.  

I've made the changes to build.sbt, and I'm working on the other ScalaDocsProvider changes now.

**Comment by TylerHorth** [comment]
@FranklinYinanDing I think I've addressed everything. Let me know if I can close this issue.

**Comment by FranklinYinanDing** [comment]
Thanks for working on it!
