### ISSUE TITLE
Root module

### ISSUE THREAD

**Issue by FranklinYinanDing** [TylerHorth/sbt-restli#11]
https://github.com/TylerHorth/sbt-restli/blob/2768470b69937b5cf03f78c4c47e48b4b08d5cb6/build.sbt#L13

May consider adding a root module to aggregate all submodules, so that it is easier to do global build/test/publish.

**Comment by TylerHorth** [comment]
Sbt creates an aggregate root project implicitly. Where this breaks down is for cross compiling. Since the root project isn't setup to crossbuild either sbt or scala versions, you need to `project` into the subproject to do so.
