### ISSUE TITLE
restliModelApi := api,     restliModelCompat := "BACKWARDS",

### ISSUE THREAD

**Issue by FranklinYinanDing** [TylerHorth/sbt-restli#9]
Can user use the default value of `restliModel` out of the box?

With the list of common settings, `restliModelCompat` could be removed, as it is using the default value.

**Comment by TylerHorth** [comment]
`restliModelApi` defaults to the current project. We could default to whatever project has the name "api" but that would be pretty fragile since you wouldn't expect changing a project name to break compilation.
